const colorData = [
  { mbti: "INFJ",
    out: "#00B26E",
    in: "#FFA8DF",
  },
  { mbti: "INTJ",
    out: "#FFA8DF",
    in: "#00B26E",
  },
  { mbti: "ESTP",
    out: "#9FEEA2",
    in: "#0272F1",
  },
  { mbti: "ESFP",
    out: "#0272F1",
    in: "#9FEEA2",
  },
  { mbti: "ENFP",
    out: "#78D9EE",
    in: "#FF9D42",
  },
  { mbti: "ENTP",
    out: "#FF9D42",
    in: "#78D9EE",
  },
  { mbti: "ISTJ",
    out: "#78D9EE",
    in: "#EFC7D6",
  },
  { mbti: "ISFJ",
    out: "#78D9EE",
    in: "#EFC7D6",
  },
  { mbti: "INFP",
    out: "#0272F1",
    in: "#B2ACF9",
  },
  { mbti: "INTP",
    out: "#B2ACF9",
    in: "#0272F1",
  },
  { mbti: "ISTP",
    out: "#9FEEA2",
    in: "#B2ACF9",
  },
  { mbti: "ISFP",
    out: "#B2ACF9",
    in: "#9FEEA2",
  },
  { mbti: "ESTJ",
    out: "#FC5013",
    in: "#78D9EE",
  },
  { mbti: "ESFJ",
    out: "#78D9EE",
    in: "#FC5013",
  },
  { mbti: "ENFJ",
    out: "#0272F2",
    in: "#EFC7D6",
  },
  { mbti: "ENTJ",
    out: "#EFC7D6",
    in: "#0272F2",
  },
];

export default colorData;
